language: android
jdk:
  - oraclejdk8

android:
    components:
        - tools
        - build-tools-25.0.2
        - android-25
        - android-6
        - extra-android-support
        - extra-android-m2repository
    licences:
        - '.+'

script:
    - ./gradlew assembleDebug assembleAndroidTest lint
